version: '3.8'

services:
  jenkins:
    build: .
    container_name: jenkins
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins-network

networks:
  jenkins-network:
    driver: bridge

volumes:
  jenkins-data:
    driver: local
    driver_opts:
      type: none
      device: "/home/verma-tv/cicd/CICD_test/jenkins"
      o: bind,rw
